cart:      
  right_left_wheel_controller:
    type: position_controllers/JointPositionController
    joint: right_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_right_wheel_controller:
    type: position_controllers/JointPositionController
    joint: right_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_right_wheel_controller:
    type: position_controllers/JointPositionController
    joint: left_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_left_wheel_controller:
    type: position_controllers/JointPositionController
    joint: left_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}