version: "3.4"

x-melodic-port: &melodic-port 11311
# x-noetic-port: &noetic-port 11311
x-ros-master-uri-env: &ros-master-uri-env ROS_MASTER_URI=http://${ROS_MASTER_DOMAIN:-ros_melodic}:11311
x-melodic-src-mapping: &melodic-src-mapping ./src/melodic/:/home/${USER}/catkin_ws/src
x-noetic-src-mapping: &noetic-src-mapping ./src/noetic/:/home/${USER}/catkin_ws/src
x-melodic-output-mapping: &melodic-ouput-mapping ./outputs/melodic/:/home/${USER}/catkin_ws/outputs
x-noetic-output-mapping: &noetic-ouput-mapping ./outputs/noetic/:/home/${USER}/catkin_ws/ouputs
# host.docker.internal:0を使う場合以下は不要
x-x11-mapping: &x11-mapping /tmp/.X11-unix:/tmp/.X11-unix:rw

x-common-setting: &common-setting
  tty: true
  # devices:
  #   - /dev/dri/card0:/dev/dri/card0
  #   - /dev/video0:/dev/video0
  networks:
    - ros_dev_external
  # TODO: moveitの実行時のために特権つけてるが限定的な権限に置き換えたい
  privileged: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  command: bash -c "catkin clean -by && catkin build && /bin/bash"

services:
  ros_melodic:
    <<: *common-setting
    build:
      context: .
      dockerfile: ./docker/melodic/Dockerfile
      args:
        BUILD_USER: ${USER}
    image: sin392/ros_melodic:latest
    container_name: ros_melodic
    volumes:
      - *melodic-src-mapping
      - *x11-mapping
      - *melodic-ouput-mapping
    ports:
      - *melodic-port
    environment:
      - DISPLAY=${DISPLAY}
      - *ros-master-uri-env

  ros_noetic:
    <<: *common-setting
    build:
      context: .
      dockerfile: ./docker/noetic/Dockerfile
      args:
        BUILD_USER: ${USER}
    image: sin392/ros_noetic:latest
    container_name: ros_noetic
    volumes:
      - *noetic-src-mapping
      - *x11-mapping
      - *noetic-ouput-mapping
    # ports:
    #   - *noetic-port
    environment:
      - DISPLAY=${DISPLAY}
      - *ros-master-uri-env

networks:
  ros_dev_external:
    external: true
