# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
  # - far_clipping_plane_distance: 5.0
  #   filtered_cloud_topic: filtered_cloud
  #   image_topic: /myrobot/left_camera/depth/image_raw
  #   max_range: 5.0
  #   max_update_rate: 1.0
  #   near_clipping_plane_distance: 1.0
  #   padding_offset: 0.03
  #   padding_scale: 4.0
  #   point_cloud_topic: /left_camera/depth/points
  #   point_subsample: 1
  #   queue_size: 5
  #   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   shadow_threshold: 0.2
  # - far_clipping_plane_distance: 5.0
  #   filtered_cloud_topic: filtered_cloud
  #   image_topic: /myrobot/right_camera/depth/image_raw
  #   max_range: 5.0
  #   max_update_rate: 1.0
  #   near_clipping_plane_distance: 1.0
  #   padding_offset: 0.03
  #   padding_scale: 4.0
  #   
  #   point_subsample: 1
  #   queue_size: 5
  #   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   shadow_threshold: 0.2
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /myrobot/body_camera/depth/color/points
    max_update_rate: 1.0
    max_range: 5.0
    padding_offset: 0.1
    padding_scale: 1.0
    point_subsample: 1
  # - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   image_topic: /body_camera/body_camera/depth/image_raw
  #   max_update_rate: 1.0
  #   far_clipping_plane_distance: 5.0
  #   near_clipping_plane_distance: 1.0
  #   padding_offset: 0.03
  #   padding_scale: 4.0
  #   queue_size: 5
  #   shadow_threshold: 0.2